# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MultipleLayersTools
                                 A QGIS plugin
 Add buttons to add tools to work on several layers and groups.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-05
        copyright            : (C) 2020 by djes
        email                : djes@free.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MultipleLayersTools class from file MultipleLayersTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .multiple_layers_tools import MultipleLayersTools
    return MultipleLayersTools(iface)
